<a href="https://colab.research.google.com/github/Tomasz199306/KursGit/blob/master/procesing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install scikit-learn

In [3]:
!pip install --upgrade scikit-learn

     |████████████████████████████████| 22.3MB 2.0MB/s 
  Found existing installation: scikit-learn 0.22.2.post1
    Uninstalling scikit-learn-0.22.2.post1:
      Successfully uninstalled scikit-learn-0.22.2.post1


In [5]:
import numpy as np
import pandas as pd
import sklearn

sklearn.__version__

'0.24.2'

In [6]:
data = {
    'size': ['XL','L','M','L','M'],
    'color': ['red','green','blue','green','red'],
    'gender': ['female', 'male','male','female','female'],
    'price': [190.0, 89.0, 99.0, 129.0, 79.0],
    'weight': [500, 450, 300, 380, 410],
    'bought': ['yes', 'no', 'yes', 'no', 'yes']
}

df_raw = pd.DataFrame(data=data)
df_raw

size  color  gender  price  weight bought
0   XL    red  female  190.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

In [7]:
df = df_raw.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   size    5 non-null      object 
 1   color   5 non-null      object 
 2   gender  5 non-null      object 
 3   price   5 non-null      float64
 4   weight  5 non-null      int64  
 5   bought  5 non-null      object 
dtypes: float64(1), int64(1), object(4)
memory usage: 368.0+ bytes


In [8]:
for col in ['size','color','gender','bought']:
  df[col] = df[col].astype('category')

df['weight'] = df['weight'].astype('float')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   size    5 non-null      category
 1   color   5 non-null      category
 2   gender  5 non-null      category
 3   price   5 non-null      float64 
 4   weight  5 non-null      float64 
 5   bought  5 non-null      category
dtypes: category(4), float64(2)
memory usage: 628.0 bytes


In [10]:
df.describe()

price      weight
count    5.000000    5.000000
mean   117.200000  408.000000
std     44.790624   75.299402
min     79.000000  300.000000
25%     89.000000  380.000000
50%     99.000000  410.000000
75%    129.000000  450.000000
max    190.000000  500.000000

In [11]:
df.describe().T

count   mean        std    min    25%    50%    75%    max
price     5.0  117.2  44.790624   79.0   89.0   99.0  129.0  190.0
weight    5.0  408.0  75.299402  300.0  380.0  410.0  450.0  500.0

In [12]:
df.describe(include=['category']).T

count unique     top freq
size       5      3       M    2
color      5      3     red    2
gender     5      2  female    3
bought     5      2     yes    3

In [13]:
df

size  color  gender  price  weight bought
0   XL    red  female  190.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue    male   99.0   300.0    yes
3    L  green  female  129.0   380.0     no
4    M    red  female   79.0   410.0    yes

In [20]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(df['bought'])
le.transform(df['bought'])

array([1, 0, 1, 0, 1])

In [21]:
le.classes_

array(['no', 'yes'], dtype=object)

In [22]:
df['bought'] = le.fit_transform(df['bought'])
df

size  color  gender  price  weight  bought
0   XL    red  female  190.0   500.0       1
1    L  green    male   89.0   450.0       0
2    M   blue    male   99.0   300.0       1
3    L  green  female  129.0   380.0       0
4    M    red  female   79.0   410.0       1

In [24]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse=False)
encoder.fit(df[['size']])

OneHotEncoder(sparse=False)

In [26]:
encoder.transform(df[['size']])

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [27]:
encoder.categories_

[array(['L', 'M', 'XL'], dtype=object)]

In [28]:
encoder = OneHotEncoder(drop='first',sparse=False)
encoder.fit(df[['size']])
encoder.transform(df[['size']])

array([[0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.]])

In [29]:
df


size  color  gender  price  weight  bought
0   XL    red  female  190.0   500.0       1
1    L  green    male   89.0   450.0       0
2    M   blue    male   99.0   300.0       1
3    L  green  female  129.0   380.0       0
4    M    red  female   79.0   410.0       1

In [30]:
le.inverse_transform(df['bought'])

array(['yes', 'no', 'yes', 'no', 'yes'], dtype=object)

In [32]:
df['bought'] = le.inverse_transform(df['bought'])
df

size  color  gender  price  weight bought
0   XL    red  female  190.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue    male   99.0   300.0    yes
3    L  green  female  129.0   380.0     no
4    M    red  female   79.0   410.0    yes

In [33]:
pd.get_dummies(data=df)

price  weight  size_L  ...  gender_male  bought_no  bought_yes
0  190.0   500.0       0  ...            0          0           1
1   89.0   450.0       1  ...            1          1           0
2   99.0   300.0       0  ...            1          0           1
3  129.0   380.0       1  ...            0          1           0
4   79.0   410.0       0  ...            0          0           1

[5 rows x 12 columns]

In [34]:
pd.get_dummies(data=df, drop_first=True)

price  weight  size_M  ...  color_red  gender_male  bought_yes
0  190.0   500.0       0  ...          1            0           1
1   89.0   450.0       0  ...          0            1           0
2   99.0   300.0       1  ...          0            1           1
3  129.0   380.0       0  ...          0            0           0
4   79.0   410.0       1  ...          1            0           1

[5 rows x 8 columns]